/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'dh_pressureboard_attempt1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "tle985x.h"

/* Infineon::Device:SDK:ADC1@0.2.9 */
#define RTE_DEVICE_SDK_ADC1
/* Infineon::Device:SDK:ADC2@0.3.5 */
#define RTE_DEVICE_SDK_ADC2
/* Infineon::Device:SDK:BOOTROM@0.2.5 */
#define RTE_DEVICE_SDK_BROM
/* Infineon::Device:SDK:CCU6@0.3.1 */
#define RTE_DEVICE_SDK_CCU6
/* Infineon::Device:SDK:GPT12E@0.2.4 */
#define RTE_DEVICE_SDK_GPT12E
/* Infineon::Device:SDK:INT@0.3.1 */
#define RTE_DEVICE_SDK_INT
/* Infineon::Device:SDK:ISR@0.3.1 */
#define RTE_DEVICE_SDK_ISR
/* Infineon::Device:SDK:LIN@0.2.5 */
#define RTE_DEVICE_SDK_LIN
/* Infineon::Device:SDK:PMU@0.2.4 */
#define RTE_DEVICE_SDK_PMU
/* Infineon::Device:SDK:PORT@0.2.4 */
#define RTE_DEVICE_SDK_PORT
/* Infineon::Device:SDK:SCU@0.4.2 */
#define RTE_DEVICE_SDK_SCU
/* Infineon::Device:SDK:TIMER2x@0.2.4 */
#define RTE_DEVICE_SDK_TIMER2X
/* Infineon::Device:SDK:UART@0.2.6 */
#define RTE_DEVICE_SDK_UART
/* Infineon::Device:SDK:WDT1@0.2.5 */
#define RTE_DEVICE_SDK_WDT1


#endif /* RTE_COMPONENTS_H */
