#!/usr/bin/env python3
"""Score a soak capture against the firmware's own reference stream.

The reference is generated by the SAME function the firmware runs:

    make -C host_tests
    ./host_tests/test_link_frame --emit-ref ref.csv 1000 0     # rate, phase

    python soak_verify.py --capture logs/run1 --reference ref.csv --rate 1000

What it checks, and why each one earns its place:

  RESOLUTION / FULL RANGE
      Which of the 10,001 deci-bar codes actually reached the tap. Phase A
      sweeps every one of them, so a hole here is a real encode or transmit
      defect, not a sampling artefact.

  VALUE-EXACT COMPARISON
      The link protocol has no sequence number (link_protocol.md §3, gate
      Q20), so the waveform has to be its own. Inside a ramp the reference is
      strictly monotonic, which makes a dropped, duplicated or reordered
      sample visible at sample granularity. Inside a hold the value repeats,
      so losses there are caught only by the run-length and timing checks
      below — that limitation is stated in the report rather than hidden.

  RAMP TIMING
      Each ramp runs a fixed wall-clock window. Duration is measured by
      COUNTING PACKETS (nominal 40 ms period), not by host timestamps: OS
      serial buffering delivers frames in chunks and would dominate the error
      on a 10-second window. Timestamps are reported alongside as a coarse
      cross-check only.

Frames are decoded with link_decoder.LinkDecoder, unchanged — it already
handles 0x7F in the payload and sliding checksum recovery.
"""
import argparse
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from link_decoder import LinkDecoder, decode_code, CODE_NAMES, VALUE_MAX  # noqa: E402

PACKET_PERIOD_MS = 40.0     # link_protocol.md §4 — nominal, rebased per sync
WORST_GAP_MS = 75.0         # one fenced stalled-ADC refresh
NO_READING = 0xFF01
BEACON_CODE = VALUE_MAX     # app_config.h SIM_AUTOSTART_BEACON_CODE


# --------------------------------------------------------------------------
# inputs
# --------------------------------------------------------------------------
def load_reference(path):
    """-> list of (index, code, seg), in index order."""
    rows = []
    with open(path) as fh:
        header = fh.readline()
        if not header.startswith("index,code,seg"):
            sys.exit("%s: not a --emit-ref reference CSV" % path)
        for line in fh:
            if not line.strip():
                continue
            i, c, s = line.split(",")
            rows.append((int(i), int(c), int(s)))
    return rows


def load_capture(prefix):
    """Read the .bin parts in order -> (bytes, [(byte_offset, t_mono)])."""
    parts = sorted(glob.glob(prefix + ".*.bin"))
    if not parts:
        if os.path.exists(prefix):
            parts = [prefix]
        else:
            sys.exit("no capture parts found for prefix %r" % prefix)
    blob = bytearray()
    stamps = []
    for p in parts:
        base = os.path.getsize(p)
        idx = p[:-4] + ".idx"
        origin = len(blob)
        with open(p, "rb") as fh:
            blob.extend(fh.read())
        if os.path.exists(idx):
            with open(idx) as fh:
                for line in fh:
                    if line.startswith("#"):
                        continue
                    f = line.split()
                    if len(f) >= 3:
                        stamps.append((origin + int(f[2]), float(f[1])))
        else:
            print("WARNING: %s missing — timing cross-check unavailable" % idx)
        del base
    return bytes(blob), stamps


# --------------------------------------------------------------------------
# structure
# --------------------------------------------------------------------------
def runs_of(codes):
    """Collapse a code sequence into [(code, count, first_pos)]."""
    out = []
    for pos, c in enumerate(codes):
        if out and out[-1][0] == c:
            out[-1][1] += 1
        else:
            out.append([c, 1, pos])
    return out


def find_beacons(dec_runs):
    """Run indices that are an autostart START BEACON.

    The beacon is full scale held for ~30 s before the profile begins. The
    profile ALSO holds at full scale (300 s in Phase A, briefly in tier 5), so
    the value alone is not enough. What identifies a beacon is that it is
    immediately followed by the profile's status block (NO_READING) — an
    adjacency that occurs nowhere inside the profile itself."""
    out = []
    for i in range(len(dec_runs) - 1):
        if dec_runs[i][0] == BEACON_CODE and dec_runs[i + 1][0] == NO_READING:
            out.append(i)
    return out


def segments_of(ref):
    """Group the reference into segments and classify each from its data.

    Deriving kind from the codes keeps this script self-contained — it needs
    no second metadata file that could drift out of step with the firmware."""
    segs = []
    for index, code, seg in ref:
        if segs and segs[-1]["seg"] == seg:
            s = segs[-1]
            s["last"] = index
            s["codes"].append(code)
        else:
            segs.append({"seg": seg, "first": index, "last": index,
                         "codes": [code]})
    for s in segs:
        cs = s["codes"]
        s["steps"] = len(cs)
        if all(c > VALUE_MAX for c in cs):
            s["kind"] = "STATUS"
        elif cs[0] == cs[-1] and len(set(cs)) == 1:
            s["kind"] = "HOLD"
        else:
            s["kind"] = "RAMP"
        s["start"] = cs[0]
        s["target"] = cs[-1]
    return segs


def align(dec_runs, ref_runs, probe=24):
    """Find where the capture starts inside the reference run sequence.

    A capture can begin anywhere in the profile, and a bare code is ambiguous
    (every value recurs). A run of consecutive distinct values is not, so we
    match a window of run codes rather than a single sample."""
    if not dec_runs:
        return None, 0
    n = min(probe, len(dec_runs))
    want = [r[0] for r in dec_runs[:n]]
    ref_codes = [r[0] for r in ref_runs]
    hits = []
    for off in range(len(ref_codes) - n + 1):
        if ref_codes[off:off + n] == want:
            hits.append(off)
            if len(hits) > 4:
                break
    if not hits:
        # The first run is usually partial (capture started mid-value); retry
        # without it before giving up.
        if n > 2:
            want2 = want[1:]
            for off in range(len(ref_codes) - len(want2) + 1):
                if ref_codes[off:off + len(want2)] == want2:
                    return off, 1
        return None, 0
    return hits[0], 0


# --------------------------------------------------------------------------
# report
# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--capture", required=True, help="prefix passed to soak_capture.py")
    ap.add_argument("--reference", required=True, help="CSV from --emit-ref")
    ap.add_argument("--rate", type=int, default=1000, help="refresh period in ms")
    ap.add_argument("--tolerance-ms", type=float, default=None,
                    help="per-ramp duration tolerance (default: 2 packet periods)")
    args = ap.parse_args()
    tol = args.tolerance_ms if args.tolerance_ms is not None else 2 * PACKET_PERIOD_MS

    ref = load_reference(args.reference)
    blob, stamps = load_capture(args.capture)
    segs = segments_of(ref)

    dec = LinkDecoder()
    codes, offsets = [], []
    # Feed in chunks so byte offsets stay recoverable for the timing check.
    CH = 4096
    for base in range(0, len(blob), CH):
        for kind, payload in dec.feed(blob[base:base + CH]):
            if kind == "frame":
                codes.append(payload)
                offsets.append(base)

    problems = []          # every check appends here; the verdict is this list

    print("=" * 72)
    print("SOAK VERIFICATION")
    print("=" * 72)
    print("capture      : %s  (%d bytes)" % (args.capture, len(blob)))
    print("reference    : %s  (%d refreshes, rate %d ms)"
          % (args.reference, len(ref), args.rate))
    print("frames ok    : %d" % dec.frames_ok)
    print("checksum err : %d      resyncs: %d      non-frame bytes: %d"
          % (dec.checksum_errors, dec.resyncs, dec.text_bytes))
    if dec.checksum_errors:
        problems.append("%d checksum error(s)" % dec.checksum_errors)
    if dec.text_bytes:
        problems.append("%d non-frame byte(s) on the wire" % dec.text_bytes)
        print("  NOTE: non-frame bytes present. Console text and packets are")
        print("        mutually exclusive, so this means the console was")
        print("        unlocked mid-run, or the tap picked up line noise.")
    if not codes:
        sys.exit("\nno decodable frames — check wiring, baud (9600) and that "
                 "the console is LOCKED")

    # ---- resolution / full range ----------------------------------------
    seen = set(c for c in codes if c <= VALUE_MAX)
    ref_vals = set(c for _, c, _ in ref if c <= VALUE_MAX)
    missing = sorted(ref_vals - seen)
    # Runs and beacons are needed by the reset logic below as well as by
    # alignment, so build them once here.
    dec_runs_all = runs_of(codes)
    ref_runs = runs_of([c for _, c, _ in ref])
    beacons = find_beacons(dec_runs_all)

    print("\n-- RESOLUTION / FULL RANGE " + "-" * 45)
    print("distinct pressure codes seen : %d" % len(seen))
    print("codes the reference expects  : %d" % len(ref_vals))
    if ref_vals:
        print("coverage                     : %.4f%%"
              % (100.0 * len(seen & ref_vals) / len(ref_vals)))
    if missing:
        problems.append("%d expected code(s) never transmitted" % len(missing))
        show = ", ".join(str(m) for m in missing[:12])
        print("MISSING %d code(s): %s%s"
              % (len(missing), show, " ..." if len(missing) > 12 else ""))
    else:
        print("every expected code was transmitted.")
    if seen:
        print("range seen                   : %d .. %d dbar (%.1f .. %.1f bar)"
              % (min(seen), max(seen), min(seen) / 10.0, max(seen) / 10.0))
    over = sorted(c for c in seen if c > VALUE_MAX)
    if over:
        problems.append("%d code(s) above the 10000 cap" % len(over))
        print("!! %d code(s) above the 10000 cap: %s" % (len(over), over[:8]))

    # ---- status codes ----------------------------------------------------
    print("\n-- STATUS CODES " + "-" * 56)
    for code, name in sorted(CODE_NAMES.items()):
        n = codes.count(code)
        print("  %-12s 0x%04X  %7d packet(s)%s"
              % (name, code, n, "" if n else "   <-- never seen"))
    # NO_READING is emitted at boot before the first sample, so an unexpected
    # one means the board reset. The profile's own status block also emits it
    # once per cycle, though — so count ONSETS and score them against how many
    # the reference itself expects, rather than treating every one as a reset.
    def onsets(seq, want):
        return sum(1 for i, c in enumerate(seq)
                   if c == want and (i == 0 or seq[i - 1] != want))

    seen_nr = onsets(codes, NO_READING)
    ref_nr = onsets([c for _, c, _ in ref], NO_READING)
    # Scale the expectation by how many times the profile ran in this capture.
    pkts_per_refresh = max(1.0, args.rate / PACKET_PERIOD_MS)
    cycles = max(1.0, len(codes) / (len(ref) * pkts_per_refresh))
    expect_nr = ref_nr * cycles
    excess = seen_nr - expect_nr
    print("  NO_READING onsets            : %d seen, ~%.0f expected from the "
          "profile's status block(s)" % (seen_nr, expect_nr))
    # Allow one extra: a capture may legitimately start mid-boot.
    resets = int(excess) if excess > 1.0 else 0
    if beacons:
        # The beacon is direct evidence of a reboot; this count is an
        # inference from the same event and would double-report it.
        print("  (reset detection is by start beacon below — this count is "
              "informational)")
    elif resets:
        problems.append("%d unexpected NO_READING onset(s) — board reset "
                        "mid-run" % resets)
        print("  UNEXPECTED onsets            : %d   <-- BOARD RESET" % resets)

    # ---- alignment + value-exact comparison ------------------------------
    # ---- start beacon ----------------------------------------------------
    print("\n-- START BEACON " + "-" * 56)
    if not beacons:
        print("none seen — console-armed build, or the capture began after the")
        print("beacon had already passed. Resets fall back to NO_READING onsets.")
        preamble = 0
    else:
        # Everything up to and including the first beacon is pre-run preamble
        # (boot NO_READING, then the beacon). Alignment starts after it, so
        # the reference stream stays exactly the profile.
        preamble = beacons[0] + 1
        b = dec_runs_all[beacons[0]]
        print("run start    : packet %d, %d packets at full scale (~%.0f s)"
              % (b[2], b[1], b[1] * PACKET_PERIOD_MS / 1000.0))
        if len(beacons) > 1:
            # Boot-only, so any further beacon is a board reset. This is direct
            # evidence, unlike inferring one from NO_READING onsets.
            problems.append("%d board reset(s) — a second start beacon means "
                            "the board rebooted mid-run" % (len(beacons) - 1))
            print("BOARD RESET  : %d further beacon(s) — the board rebooted "
                  "mid-run" % (len(beacons) - 1))
            for i in beacons[1:]:
                print("               reset at packet %d (~%.1f s in)"
                      % (dec_runs_all[i][2],
                         dec_runs_all[i][2] * PACKET_PERIOD_MS / 1000.0))
        else:
            print("resets       : none (exactly one beacon, as expected)")

    dec_runs = dec_runs_all[preamble:]
    off, skip = align(dec_runs, ref_runs)
    print("\n-- VALUE-EXACT COMPARISON " + "-" * 46)
    if off is None:
        problems.append("capture could not be aligned to the reference")
        print("could not align the capture to the reference.")
        print("  The first %d decoded values do not appear as a run in the"
              % min(24, len(dec_runs)))
        print("  reference. Check --rate matches the RATE used, and that the")
        print("  reference phase matches what SIM was set to.")
    else:
        print("aligned at reference run %d (reference index %d)"
              % (off, ref_runs[off][2]))
        mismatch = None
        matched = 0
        for k in range(len(dec_runs) - skip):
            d = dec_runs[k + skip]
            r_i = off + k
            if r_i >= len(ref_runs):
                break
            if d[0] != ref_runs[r_i][0]:
                mismatch = (k + skip, d[0], ref_runs[r_i][0], ref_runs[r_i][2])
                break
            matched += 1
        print("consecutive matching runs    : %d of %d decoded"
              % (matched, len(dec_runs) - skip))
        if mismatch:
            k, got, want, ridx = mismatch
            problems.append("value divergence at reference index %d "
                            "(got %d, expected %d)" % (ridx, got, want))
            print("FIRST DIVERGENCE at decoded run %d: got %d, expected %d "
                  "(reference index %d)" % (k, got, want, ridx))
        else:
            print("no divergence — every decoded value matched the reference.")

        # Dropped-sample detection inside ramps: a reference run that got no
        # packets at all. Holds are excluded because a repeated value cannot
        # be told apart from a lost one by value.
        ramp_idx = set()
        for s in segs:
            if s["kind"] == "RAMP":
                ramp_idx.update(range(s["first"], s["last"] + 1))
        short = 0
        expect_pkts = args.rate / PACKET_PERIOD_MS
        for k in range(matched):
            r = ref_runs[off + k]
            d = dec_runs[k + skip]
            if r[2] in ramp_idx and d[1] < max(1, int(expect_pkts * 0.5)):
                short += 1
        if short:
            problems.append("%d ramp value(s) carried under half the expected "
                            "packet count" % short)
        print("ramp values with <50%% of the expected %.0f packets : %d"
              % (expect_pkts, short))
        print("NOTE: losses inside HOLD segments cannot be detected by value")
        print("      (the value repeats); the timing section below covers them.")

    # ---- ramp timing -----------------------------------------------------
    print("\n-- RAMP TIMING (packet-counted) " + "-" * 40)
    if off is None:
        print("skipped — no alignment.")
    else:
        # A ramp's final value and the hold that follows it are the SAME code,
        # so they collapse into one run; billing that whole run to the ramp
        # would add the hold's duration to every measurement. Anchor instead
        # on two reference positions that are always run boundaries:
        #   r1 = first index in the segment whose value differs from the start
        #   r2 = first index in the segment that reaches the target
        # The span between them is (r2 - r1) refreshes, which is the ramp's
        # window less one refresh — reported back as a full window below.
        # Deriving both from the reference keeps this correct at any RATE,
        # including fractional dbar/refresh rates where a ramp begins with a
        # plateau at its start value.
        by_first = {}
        for ri, r in enumerate(ref_runs):
            by_first.setdefault(r[2], ri)

        def pkt_pos(ref_index):
            """Packet offset of the decoded run starting at this ref index."""
            ri = by_first.get(ref_index)
            if ri is None:
                return None
            di = ri - off + skip
            if di < 0 or di >= len(dec_runs):
                return None
            return dec_runs[di][2]

        print("%-5s %7s %7s %10s %10s %9s  %s"
              % ("seg", "start", "target", "spec_ms", "meas_ms", "err_ms",
                 "verdict"))
        worst = 0.0
        checked = 0
        skipped = 0
        out_of_tol = 0
        for sg in segs:
            if sg["kind"] != "RAMP":
                continue
            codes_seg = sg["codes"]
            vt = codes_seg[-1]
            # The reference value immediately BEFORE the segment — not the
            # segment's own first value, which has already moved off it. At
            # RATE 1000 the ramp moves on its very first refresh; at rates
            # where the slew is under 1 dbar/refresh it plateaus first, and
            # this finds the real moment of departure either way.
            v_prev = ref[sg["first"] - 1][1] if sg["first"] > 0 else codes_seg[0]
            i_chg = next((sg["first"] + n for n, c in enumerate(codes_seg)
                          if c != v_prev), None)
            i_tgt = next((sg["first"] + n for n, c in enumerate(codes_seg)
                          if c == vt), None)
            if i_chg is None or i_tgt is None or i_tgt <= i_chg:
                skipped += 1
                continue
            p1, p2 = pkt_pos(i_chg), pkt_pos(i_tgt)
            if p1 is None or p2 is None or p2 <= p1:
                skipped += 1
                continue
            spec = sg["steps"] * args.rate
            # span + one refresh == the full window, matching spec_ms
            meas = (p2 - p1) * PACKET_PERIOD_MS + args.rate
            err = meas - spec
            ok = abs(err) <= max(tol, 0.02 * spec)
            if not ok:
                out_of_tol += 1
            worst = max(worst, abs(err))
            checked += 1
            print("%-5d %7d %7d %10d %10.0f %9.0f  %s"
                  % (sg["seg"], sg["start"], sg["target"], spec, meas, err,
                     "ok" if ok else "OUT OF TOLERANCE"))
        if checked == 0:
            print("no complete ramp segments in this capture.")
        else:
            if out_of_tol:
                problems.append("%d ramp(s) outside the duration tolerance"
                                % out_of_tol)
            print("\n%d ramp(s) measured, worst |error| = %.0f ms "
                  "(tolerance %.0f ms or 2%%)" % (checked, worst, tol))
        if skipped:
            print("%d ramp(s) not measurable in this capture (partial or "
                  "not reached)." % skipped)

    # ---- inter-packet timing (coarse) ------------------------------------
    print("\n-- INTER-PACKET TIMING (coarse, host timestamps) " + "-" * 23)
    if len(stamps) < 2:
        print("no .idx sidecars — skipped.")
    else:
        gaps = []
        for i in range(1, len(stamps)):
            dt = (stamps[i][1] - stamps[i - 1][1]) * 1000.0
            nbytes = stamps[i][0] - stamps[i - 1][0]
            if nbytes == 0 and dt > WORST_GAP_MS:
                gaps.append(dt)
        if gaps:
            gaps.sort()
            print("read intervals with no bytes and > %.0f ms : %d"
                  % (WORST_GAP_MS, len(gaps)))
            print("longest silence                          : %.0f ms" % gaps[-1])
            problems.append("%d silence(s) beyond the %.0f ms worst "
                            "legitimate gap" % (len(gaps), WORST_GAP_MS))
            if gaps[-1] >= 500.0:
                print("  >= 500 ms: this is the logger's staleness case "
                      "(link_protocol.md §5).")
        else:
            print("no silence beyond the %.0f ms worst legitimate gap."
                  % WORST_GAP_MS)
        span = stamps[-1][1] - stamps[0][1]
        if span > 0:
            print("capture span %.1f s, %d frames -> %.2f packets/s "
                  "(nominal 25.0)" % (span, dec.frames_ok, dec.frames_ok / span))

    # ---- verdict ---------------------------------------------------------
    print("\n" + "=" * 72)
    if problems:
        print("RESULT: FAIL — %d finding(s)" % len(problems))
        for n, why in enumerate(problems, 1):
            print("  %d. %s" % (n, why))
    else:
        print("RESULT: PASS")
    print("=" * 72)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
